import { createAppSlice } from "../../createAppSlice";

const initialState = {
  previewAsset: {
    id: "",
    name: "",
    description: "",
    asset_type: "",
    asset_url: "",
    thumbnail_url: "",
    status: "idle",
    created_at: "",
    updated_at: "",
  },
  assets: [
    {
      uuid: "1",
      penggunaan: "pertanian",
      skpd: "Dinas Pertanian",
      kecamatan: "Ngemplak",
      desa: "Ngemplak",
      alamat: "Jl. Raya Ngemplak",
      leglitas: "Sertifikat",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2021-08-21",
    },
    {
      uuid: "2",
      penggunaan: "perumahan",
      skpd: "Dinas Perumahan dan Permukiman",
      kecamatan: "Depok",
      desa: "Caturharjo",
      alamat: "Jl. Kaliurang KM 7",
      leglitas: "SHM",
      kasus: true,
      uraian_kasus: "Sengketa lahan dengan warga",
      updatedAt: "2021-09-10",
    },
    {
      uuid: "3",
      penggunaan: "perdagangan",
      skpd: "Dinas Perdagangan",
      kecamatan: "Sleman",
      desa: "Tridadi",
      alamat: "Jl. Magelang KM 10",
      leglitas: "Sertifikat",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2021-10-05",
    },
    {
      uuid: "4",
      penggunaan: "industri",
      skpd: "Dinas Perindustrian",
      kecamatan: "Mlati",
      desa: "Tirtoadi",
      alamat: "Jl. Magelang KM 8",
      leglitas: "SHGB",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2021-11-15",
    },
    {
      uuid: "5",
      penggunaan: "pariwisata",
      skpd: "Dinas Pariwisata",
      kecamatan: "Pakem",
      desa: "Hargobinangun",
      alamat: "Jl. Kaliurang KM 20",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Tumpang tindih dengan lahan warga",
      updatedAt: "2022-01-12",
    },
    {
      uuid: "6",
      penggunaan: "kesehatan",
      skpd: "Dinas Kesehatan",
      kecamatan: "Gamping",
      desa: "Ambarketawang",
      alamat: "Jl. Wates KM 5",
      leglitas: "Sertifikat",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2022-03-07",
    },
    {
      uuid: "7",
      penggunaan: "pendidikan",
      skpd: "Dinas Pendidikan",
      kecamatan: "Godean",
      desa: "Sidokarto",
      alamat: "Jl. Godean KM 8",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Sengketa dengan pihak ketiga",
      updatedAt: "2022-04-18",
    },
    {
      uuid: "8",
      penggunaan: "perikanan",
      skpd: "Dinas Kelautan dan Perikanan",
      kecamatan: "Berbah",
      desa: "Kalitirto",
      alamat: "Jl. Berbah - Prambanan",
      leglitas: "SHM",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2022-05-23",
    },
    {
      uuid: "9",
      penggunaan: "kehutanan",
      skpd: "Dinas Kehutanan",
      kecamatan: "Tempel",
      desa: "Lumbungrejo",
      alamat: "Jl. Tempel - Turi",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Pelanggaran kawasan hutan lindung",
      updatedAt: "2022-07-14",
    },
    {
      uuid: "10",
      penggunaan: "transportasi",
      skpd: "Dinas Perhubungan",
      kecamatan: "Kalasan",
      desa: "Tirtomartani",
      alamat: "Jl. Solo KM 10",
      leglitas: "SHGB",
      kasus: false,
      uraian_kasus: "",
      updatedAt: "2022-08-29",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
    {
      uuid: "11",
      penggunaan: "pertambangan",
      skpd: "Dinas Energi dan Sumber Daya Mineral",
      kecamatan: "Prambanan",
      desa: "Bokoharjo",
      alamat: "Jl. Prambanan - Piyungan",
      leglitas: "Sertifikat",
      kasus: true,
      uraian_kasus: "Izin tambang yang belum lengkap",
      updatedAt: "2022-09-17",
    },
  ],
};

export const assetSlice = createAppSlice({
  name: "asset",
  initialState,
  reducers: (create) => ({}),
  selectors: {
    selectPreviewAsset: (state) => state.previewAsset,
    selectAssets: (state) => state.assets,
  },
});

export const {} = assetSlice.actions;

export const { selectPreviewAsset, selectAssets } = assetSlice.selectors;
